import { getDbClient } from './client.js';

/**
 * Seed the database with sample data.
 * Should be called after initDatabase().
 */
export async function seedSampleData(): Promise<void> {
  const client = getDbClient();

  // === projects ===
  await client.batch([
    { sql: `INSERT INTO projects (id, name, description, git_url, local_path, created_at, updated_at) VALUES (1, 'DevOps 看板系统', '基于 AI 代理的 DevOps 看板管理系统，支持任务自动化执行', 'https://github.com/example/devops-kanban.git', '/home/workspace/devops-kanban', '2026-03-17T07:03:51.577Z', '2026-03-18T03:32:51.735Z')` },
    { sql: `INSERT INTO projects (id, name, description, git_url, local_path, created_at, updated_at) VALUES (2, '电商平台重构', '新一代电商平台重构项目，支持高并发场景', 'https://github.com/example/ecommerce-platform.git', '/home/workspace/ecommerce-platform', '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO projects (id, name, description, git_url, local_path, created_at, updated_at) VALUES (3, '数据分析平台', '企业级数据分析与可视化平台', 'https://github.com/example/data-analytics.git', '/home/workspace/data-analytics', '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
  ], 'write');

  // === iterations ===
  await client.batch([
    { sql: `INSERT INTO iterations (id, project_id, name, goal, status, start_date, end_date, created_at, updated_at) VALUES (1, 1, '26.3.0', '完成基础功能开发', 'ACTIVE', '2026-03-01', '2026-03-31', '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO iterations (id, project_id, name, goal, status, start_date, end_date, created_at, updated_at) VALUES (2, 1, '26.4.0', '完成高级功能开发', 'PLANNED', '2026-04-01', '2026-04-30', '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
  ], 'write');

  // === agents ===
  await client.batch([
    { sql: `INSERT INTO agents (id, name, executorType, role, description, enabled, skills, created_at, updated_at) VALUES (1, '架构师', 'CLAUDE_CODE', 'ARCHITECT', '负责系统架构设计与技术方案评审', 1, '[]', '2026-03-17T00:00:00.000Z', '2026-03-31T00:00:00.000Z')` },
    { sql: `INSERT INTO agents (id, name, executorType, role, description, enabled, skills, created_at, updated_at) VALUES (2, '后端开发', 'CLAUDE_CODE', 'BACKEND_DEV', '负责后端服务开发与接口实现', 1, '[]', '2026-03-17T00:00:00.000Z', '2026-03-31T00:00:00.000Z')` },
    { sql: `INSERT INTO agents (id, name, executorType, role, description, enabled, skills, created_at, updated_at) VALUES (3, '前端开发', 'CLAUDE_CODE', 'FRONTEND_DEV', '负责前端页面开发与交互实现', 1, '[]', '2026-03-17T00:00:00.000Z', '2026-03-31T00:00:00.000Z')` },
    { sql: `INSERT INTO agents (id, name, executorType, role, description, enabled, skills, created_at, updated_at) VALUES (4, '测试工程师', 'CLAUDE_CODE', 'QA_ENGINEER', '负责测试验证与质量保障', 1, '[]', '2026-03-17T00:00:00.000Z', '2026-03-31T00:00:00.000Z')` },
  ], 'write');

  // === workflow_templates ===
  await client.batch([
    { sql: `INSERT INTO workflow_templates (id, template_id, name, steps, created_at, updated_at) VALUES (1, 'workflow-v1', '默认工作流', '[{"id":"solution-design","name":"头脑风暴设计","instructionPrompt":"使用头脑风暴Skill思考。先完成 Spec-Driven 方案设计。必须基于任务上下文输出可直接执行的设计结果，并将设计文档写入 docs：1）明确目标、范围与验收标准；2）梳理用户场景、边界条件与异常场景；3）说明关键约束、依赖与风险；4）给出实现思路、模块改动点与任务拆分；5）定义测试策略、关键测试用例与完成标准；6）列出需要前置确认的问题。最后输出可供下游步骤直接消费的 summary。","agentId":1},{"id":"feature-development","name":"开发实现","instructionPrompt":"基于上游设计文档与 summary，按 TDD 完成开发实现。要求：1）先对齐验收标准与测试用例；2）优先补齐或新增失败测试，再完成实现并让相关测试通过；3）严格按设计范围修改，避免无关改动；4）优先复用现有能力与实现模式；5）必要时同步更新文档、配置或脚本；6）总结核心改动点、影响范围、测试执行结果与遗留问题。最后输出可供测试阶段直接消费的 summary。","agentId":2},{"id":"qa-validation","name":"测试验证","instructionPrompt":"基于上游设计文档、开发 summary、代码改动与测试结果执行测试验证。至少覆盖：1）验收标准是否全部满足；2）新增或修改测试是否覆盖核心路径、边界场景与异常场景；3）相关回归是否受影响；4）发现的问题、复现方式与影响判断；5）当前结果是否允许进入评审。最后输出可供评审阶段直接消费的 summary。","agentId":4},{"id":"final-review","name":"结果评审","instructionPrompt":"基于前序设计文档、各步骤 summary、代码 diff 与测试结果完成最终评审。重点确认：1）实现是否满足规格、范围与验收标准；2）设计、实现与测试是否保持一致；3）测试策略与测试结果是否足以支撑交付；4）是否存在明显质量、安全或可维护性风险；5）是否还有阻塞交付的问题；6）给出明确评审结论与后续处理建议。","agentId":1}]', '2026-03-27T00:00:00.000Z', '2026-03-31T01:05:56.698Z')` },
    { sql: `INSERT INTO workflow_templates (id, template_id, name, steps, created_at, updated_at) VALUES (2, 'dev-feature-sdd-tdd-v1', '研发交付：标准功能开发', '[{"id":"feature-sdd-requirement-clarification","name":"SDD 需求澄清与验收定义","instructionPrompt":"你当前负责标准功能开发交付的 SDD 需求澄清与验收定义阶段。","agentId":1},{"id":"feature-sdd-solution-design","name":"SDD 方案设计与任务拆解","instructionPrompt":"你当前负责标准功能开发交付的 SDD 方案设计与任务拆解阶段。","agentId":1},{"id":"feature-tdd-test-design","name":"TDD 测试先行设计","instructionPrompt":"你当前负责标准功能开发交付的 TDD 测试先行设计阶段。","agentId":4},{"id":"feature-tdd-minimal-implementation","name":"TDD 最小实现","instructionPrompt":"你当前负责标准功能开发交付的 TDD 最小实现阶段。","agentId":2},{"id":"feature-automation-validation","name":"自动化测试与回归验证","instructionPrompt":"你当前负责标准功能开发交付的自动化测试与回归验证阶段。","agentId":4},{"id":"feature-real-frontend-validation","name":"真实前端验收","instructionPrompt":"你当前负责标准功能开发交付的真实前端验收阶段。","agentId":4},{"id":"feature-delivery-review","name":"交付评审","instructionPrompt":"你当前负责标准功能开发交付的交付评审阶段。","agentId":1}]', '2026-03-30T00:00:00.000Z', '2026-03-31T01:05:18.860Z')` },
    { sql: `INSERT INTO workflow_templates (id, template_id, name, steps, created_at, updated_at) VALUES (3, 'frontend-delivery-sdd-tdd-v1', '研发交付：前端页面/交互', '[{"id":"frontend-sdd-scenario-definition","name":"SDD 交互需求与验收场景定义","instructionPrompt":"你当前负责前端页面/交互交付的 SDD 交互需求与验收场景定义阶段。","agentId":1},{"id":"frontend-sdd-ui-design","name":"SDD 前端方案设计","instructionPrompt":"你当前负责前端页面/交互交付的 SDD 前端方案设计阶段。","agentId":1},{"id":"frontend-tdd-test-design","name":"TDD 测试设计与前端验证脚本","instructionPrompt":"你当前负责前端页面/交互交付的 TDD 测试设计与前端验证脚本阶段。","agentId":4},{"id":"frontend-tdd-implementation","name":"TDD 页面实现","instructionPrompt":"你当前负责前端页面/交互交付的 TDD 页面实现阶段。","agentId":2},{"id":"frontend-automation-validation","name":"自动化测试执行","instructionPrompt":"你当前负责前端页面/交互交付的自动化测试执行阶段。","agentId":4},{"id":"frontend-real-ui-validation","name":"真实前端走查验收","instructionPrompt":"你当前负责前端页面/交互交付的真实前端走查验收阶段。","agentId":4},{"id":"frontend-release-review","name":"发布评审","instructionPrompt":"你当前负责前端页面/交互交付的发布评审阶段。","agentId":1}]', '2026-03-30T00:00:00.000Z', '2026-03-31T01:05:09.270Z')` },
    { sql: `INSERT INTO workflow_templates (id, template_id, name, steps, created_at, updated_at) VALUES (4, 'bugfix-sdd-tdd-v1', '研发交付：缺陷修复与防回归', '[{"id":"bugfix-sdd-problem-definition","name":"SDD 问题澄清与复现定义","instructionPrompt":"你当前负责缺陷修复与防回归交付的 SDD 问题澄清与复现定义阶段。","agentId":1},{"id":"bugfix-sdd-root-cause-design","name":"SDD 根因与修复设计","instructionPrompt":"你当前负责缺陷修复与防回归交付的 SDD 根因与修复设计阶段。","agentId":1},{"id":"bugfix-tdd-regression-test-design","name":"TDD 失败测试补齐","instructionPrompt":"你当前负责缺陷修复与防回归交付的 TDD 失败测试补齐阶段。","agentId":4},{"id":"bugfix-tdd-minimal-fix","name":"TDD 最小修复实现","instructionPrompt":"你当前负责缺陷修复与防回归交付的 TDD 最小修复实现阶段。","agentId":2},{"id":"bugfix-automation-regression-validation","name":"自动化回归验证","instructionPrompt":"你当前负责缺陷修复与防回归交付的自动化回归验证阶段。","agentId":4},{"id":"bugfix-real-frontend-validation","name":"真实前端复现与验收","instructionPrompt":"你当前负责缺陷修复与防回归交付的真实前端复现与验收阶段。","agentId":4},{"id":"bugfix-delivery-review","name":"修复交付评审","instructionPrompt":"你当前负责缺陷修复与防回归交付的修复交付评审阶段。","agentId":1}]', '2026-03-30T00:00:00.000Z', '2026-03-31T01:05:14.558Z')` },
  ], 'write');

  // === workflow_runs ===
  await client.batch([
    { sql: `INSERT INTO workflow_runs (id, task_id, workflow_template_id, workflow_template_snapshot, mastra_run_id, status, current_step, steps, worktree_path, branch, context, created_at, updated_at) VALUES (1, 1, 'workflow-v1', '{"template_id":"workflow-v1","name":"默认工作流","steps":[{"id":"solution-design","name":"头脑风暴设计","agentId":1},{"id":"feature-development","name":"开发实现","agentId":2},{"id":"qa-validation","name":"测试验证","agentId":4},{"id":"final-review","name":"结果评审","agentId":1}]}', NULL, 'COMPLETED', 'final-review', '[{"step_id":"solution-design","name":"头脑风暴设计","status":"COMPLETED","started_at":"2026-03-17T08:00:00.000Z","completed_at":"2026-03-17T08:15:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"完成项目实体类设计方案，明确属性定义与模块边界。"},{"step_id":"feature-development","name":"开发实现","status":"COMPLETED","started_at":"2026-03-17T08:15:00.000Z","completed_at":"2026-03-17T08:30:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"实现 Project 实体类，包含所有基本属性和关系定义。"},{"step_id":"qa-validation","name":"测试验证","status":"COMPLETED","started_at":"2026-03-17T08:30:00.000Z","completed_at":"2026-03-17T08:45:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"所有测试通过，实体类属性完整，类型定义正确。"},{"step_id":"final-review","name":"结果评审","status":"COMPLETED","started_at":"2026-03-17T08:45:00.000Z","completed_at":"2026-03-17T09:00:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"评审通过，实现满足设计要求，无遗留问题。"}]', '/tmp/worktree-task-1', 'task/1', '{}', '2026-03-17T08:00:00.000Z', '2026-03-17T09:00:00.000Z')` },
    { sql: `INSERT INTO workflow_runs (id, task_id, workflow_template_id, workflow_template_snapshot, mastra_run_id, status, current_step, steps, worktree_path, branch, context, created_at, updated_at) VALUES (2, 3, 'dev-feature-sdd-tdd-v1', '{"template_id":"dev-feature-sdd-tdd-v1","name":"研发交付：标准功能开发","steps":[{"id":"feature-sdd-requirement-clarification","name":"SDD 需求澄清与验收定义","agentId":1},{"id":"feature-sdd-solution-design","name":"SDD 方案设计与任务拆解","agentId":1},{"id":"feature-tdd-test-design","name":"TDD 测试先行设计","agentId":4},{"id":"feature-tdd-minimal-implementation","name":"TDD 最小实现","agentId":2},{"id":"feature-automation-validation","name":"自动化测试与回归验证","agentId":4},{"id":"feature-real-frontend-validation","name":"真实前端验收","agentId":4},{"id":"feature-delivery-review","name":"交付评审","agentId":1}]}', NULL, 'RUNNING', 'feature-tdd-minimal-implementation', '[{"step_id":"feature-sdd-requirement-clarification","name":"SDD 需求澄清与验收定义","status":"COMPLETED","started_at":"2026-03-20T10:00:00.000Z","completed_at":"2026-03-20T10:20:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"明确 CRUD API 需求范围，定义验收标准和关键场景。"},{"step_id":"feature-sdd-solution-design","name":"SDD 方案设计与任务拆解","status":"COMPLETED","started_at":"2026-03-20T10:20:00.000Z","completed_at":"2026-03-20T10:45:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"完成方案设计，拆解为路由层、服务层、仓库层三个阶段。"},{"step_id":"feature-tdd-test-design","name":"TDD 测试先行设计","status":"COMPLETED","started_at":"2026-03-20T10:45:00.000Z","completed_at":"2026-03-20T11:10:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"定义 12 个失败测试用例，覆盖 CRUD 核心路径和边界场景。"},{"step_id":"feature-tdd-minimal-implementation","name":"TDD 最小实现","status":"RUNNING","started_at":"2026-03-20T11:10:00.000Z","completed_at":null,"retry_count":0,"error":null,"session_id":null,"summary":null},{"step_id":"feature-automation-validation","name":"自动化测试与回归验证","status":"PENDING","started_at":null,"completed_at":null,"retry_count":0,"error":null,"session_id":null,"summary":null},{"step_id":"feature-real-frontend-validation","name":"真实前端验收","status":"PENDING","started_at":null,"completed_at":null,"retry_count":0,"error":null,"session_id":null,"summary":null},{"step_id":"feature-delivery-review","name":"交付评审","status":"PENDING","started_at":null,"completed_at":null,"retry_count":0,"error":null,"session_id":null,"summary":null}]', '/tmp/worktree-task-3', 'task/3', '{}', '2026-03-20T10:00:00.000Z', '2026-03-20T11:10:00.000Z')` },
    { sql: `INSERT INTO workflow_runs (id, task_id, workflow_template_id, workflow_template_snapshot, mastra_run_id, status, current_step, steps, worktree_path, branch, context, created_at, updated_at) VALUES (3, 5, 'frontend-delivery-sdd-tdd-v1', '{"template_id":"frontend-delivery-sdd-tdd-v1","name":"研发交付：前端页面/交互","steps":[{"id":"frontend-sdd-scenario-definition","name":"SDD 交互需求与验收场景定义","agentId":1},{"id":"frontend-sdd-ui-design","name":"SDD 前端方案设计","agentId":1},{"id":"frontend-tdd-test-design","name":"TDD 测试设计与前端验证脚本","agentId":4},{"id":"frontend-tdd-implementation","name":"TDD 页面实现","agentId":2},{"id":"frontend-automation-validation","name":"自动化测试执行","agentId":4},{"id":"frontend-real-ui-validation","name":"真实前端走查验收","agentId":4},{"id":"frontend-release-review","name":"发布评审","agentId":1}]}', NULL, 'FAILED', 'frontend-tdd-implementation', '[{"step_id":"frontend-sdd-scenario-definition","name":"SDD 交互需求与验收场景定义","status":"COMPLETED","started_at":"2026-03-22T09:00:00.000Z","completed_at":"2026-03-22T09:25:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"梳理拖拽交互场景，定义拖拽开始、进行中、结束三种状态的验收标准。"},{"step_id":"frontend-sdd-ui-design","name":"SDD 前端方案设计","status":"COMPLETED","started_at":"2026-03-22T09:25:00.000Z","completed_at":"2026-03-22T09:50:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"完成前端方案设计，基于 Vue 3 + dnd-kit 实现拖拽组件。"},{"step_id":"frontend-tdd-test-design","name":"TDD 测试设计与前端验证脚本","status":"COMPLETED","started_at":"2026-03-22T09:50:00.000Z","completed_at":"2026-03-22T10:15:00.000Z","retry_count":0,"error":null,"session_id":null,"summary":"定义 8 个组件测试和 5 个前端验证脚本。"},{"step_id":"frontend-tdd-implementation","name":"TDD 页面实现","status":"FAILED","started_at":"2026-03-22T10:15:00.000Z","completed_at":"2026-03-22T10:40:00.000Z","retry_count":1,"error":"拖拽组件在移动端兼容性问题未解决，需要重新设计方案。","session_id":null,"summary":"部分实现完成，移动端触摸事件处理存在兼容性问题。"},{"step_id":"frontend-automation-validation","name":"自动化测试执行","status":"PENDING","started_at":null,"completed_at":null,"retry_count":0,"error":null,"session_id":null,"summary":null},{"step_id":"frontend-real-ui-validation","name":"真实前端走查验收","status":"PENDING","started_at":null,"completed_at":null,"retry_count":0,"error":null,"session_id":null,"summary":null},{"step_id":"frontend-release-review","name":"发布评审","status":"PENDING","started_at":null,"completed_at":null,"retry_count":0,"error":null,"session_id":null,"summary":null}]', '/tmp/worktree-task-5', 'task/5', '{}', '2026-03-22T09:00:00.000Z', '2026-03-22T10:40:00.000Z')` },
  ], 'write');

  // === tasks ===
  await client.batch([
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (1, '创建项目实体类', '定义 Project 实体类，包含基本属性和关系', 1, 'DONE', 'HIGH', 'manual', '["backend"]', 0, 1, 1, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (2, '实现项目 Repository', '实现项目数据访问层，支持文件存储', 1, 'DONE', 'HIGH', 'manual', '["backend"]', 1, 1, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (3, '实现项目 API 接口', '创建 RESTful API 接口，支持 CRUD 操作', 1, 'IN_PROGRESS', 'HIGH', 'manual', '["backend"]', 2, 1, 2, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (4, '设计看板 UI 布局', '设计看板页面的 UI 布局和交互效果', 1, 'DONE', 'MEDIUM', 'manual', '["frontend"]', 3, 1, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (5, '实现拖拽功能', '实现任务卡片的拖拽排序与状态变更功能', 1, 'IN_PROGRESS', 'HIGH', 'manual', '["frontend"]', 4, 1, 3, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (6, '调研 AI 代理方案', '调研可行的 AI 代理集成方案，输出技术选型报告', 1, 'DONE', 'HIGH', 'manual', '["research"]', 5, 1, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (7, '配置 WebSocket 服务', '配置 WebSocket 服务端，支持实时消息推送', 1, 'BLOCKED', 'MEDIUM', 'manual', '["backend"]', 6, 1, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (8, '修复会话连接断开问题', '修复 WebSocket 会话在长时间空闲后自动断开的缺陷', 1, 'TODO', 'MEDIUM', 'manual', '["bugfix","backend"]', 7, 1, NULL, NULL, NULL, '2026-03-20T07:03:51.577Z', '2026-03-20T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (9, '设计用户数据库表', '设计用户、角色、权限相关的数据库表结构', 2, 'DONE', 'CRITICAL', 'manual', '["backend"]', 0, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (10, '实现 JWT 认证', '实现 JWT Token 的生成和验证逻辑', 2, 'IN_PROGRESS', 'CRITICAL', 'manual', '["backend","security"]', 1, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (11, '创建商品 API', '实现商品管理的 RESTful API', 2, 'TODO', 'HIGH', 'manual', '["backend"]', 2, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (12, '实现库存预警逻辑', '当库存低于阈值时触发预警通知', 2, 'TODO', 'MEDIUM', 'manual', '["backend"]', 3, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (13, '实现 MySQL 连接器', '实现 MySQL 数据库连接和数据读取', 3, 'DONE', 'HIGH', 'manual', '["backend"]', 0, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (14, '实现 PostgreSQL 连接器', '实现 PostgreSQL 数据库连接和数据读取', 3, 'IN_PROGRESS', 'HIGH', 'manual', '["backend"]', 1, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (15, '集成图表库', '集成 ECharts 并实现基础图表类型', 3, 'TODO', 'MEDIUM', 'manual', '["frontend"]', 2, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
    { sql: `INSERT INTO tasks (id, title, description, project_id, status, priority, source, labels, "order", iteration_id, workflow_run_id, worktree_path, worktree_branch, created_at, updated_at) VALUES (16, '实现仪表盘配置', '支持用户自定义仪表盘布局和图表', 3, 'TODO', 'LOW', 'manual', '["frontend"]', 3, NULL, NULL, NULL, NULL, '2026-03-17T07:03:51.577Z', '2026-03-17T07:03:51.577Z')` },
  ], 'write');

  // === task_sources ===
  await client.batch([
    { sql: `INSERT INTO task_sources (id, name, type, project_id, config, enabled, last_sync_at, created_at, updated_at) VALUES (1, 'git', 'GITHUB', 1, '{"repo":"https://github.com/example/your-repo.git","token":"","state":"open"}', 1, '2026-03-18T06:30:45.183Z', '2026-03-18T11:36:52.653Z', '2026-03-18T06:30:45.183Z')` },
  ], 'write');

  console.log('Sample data seeded successfully.');
}