/**
 * Mastra instance initialization
 *
 * Provides a singleton Mastra instance with LibSQLStore for workflow state persistence.
 */

import path from 'path';
import { z } from 'zod';
import { Mastra } from '@mastra/core';
import { LibSQLStore } from '@mastra/libsql';
import { createStep, createWorkflow } from '@mastra/core/workflows';
import { STORAGE_PATH } from '../config/index.js';

let _mastra = null;
let _devWorkflow = null;
let _initialized = false;

/**
 * Initialize Mastra and register workflows.
 * Call once at server startup.
 */
export async function initWorkflows() {
  if (_initialized) return;

  // 1. Create Mastra instance with storage
  const dbPath = path.join(STORAGE_PATH, 'mastra.db');
  _mastra = new Mastra({
    storage: new LibSQLStore({
      id: 'kanban-workflow-store',
      url: `file:${dbPath}`,
    }),
  });

  // 2. Build dev workflow
  _devWorkflow = buildDevWorkflow();

  _initialized = true;
  console.log('[Workflow] Mastra initialized with LibSQLStore');
}

function buildDevWorkflow() {
  const requirementDesignStep = createStep({
    id: 'requirement-design',
    inputSchema: z.object({
      taskId: z.number(),
      taskTitle: z.string(),
      taskDescription: z.string(),
      requirementContent: z.string(),
      worktreePath: z.string(),
    }),
    outputSchema: z.object({
      designDocPath: z.string(),
      designDocContent: z.string(),
    }),
    execute: async ({ inputData }) => {
      console.log(`[Workflow] Step "requirement-design" started`);
      console.log(`[Workflow]   Task: #${inputData.taskId} - ${inputData.taskTitle}`);
      console.log(`[Workflow]   Worktree: ${inputData.worktreePath}`);

      // TODO: Replace with real Claude Code CLI spawn
      await new Promise((resolve) => setTimeout(resolve, 60000));

      const designDocContent = [
        `# Design Document: ${inputData.taskTitle}`,
        '',
        '## Overview',
        inputData.taskDescription,
        '',
        '## Requirements',
        inputData.requirementContent,
        '',
        '## Technical Design',
        '- [Mock] This is a mock design document generated by the workflow.',
        '',
        `Generated at: ${new Date().toISOString()}`,
      ].join('\n');

      console.log(`[Workflow] Step "requirement-design" completed`);
      return { designDocPath: 'docs/design.md', designDocContent };
    },
  });

  const codeDevelopmentStep = createStep({
    id: 'code-development',
    inputSchema: z.object({
      designDocPath: z.string(),
      designDocContent: z.string(),
    }),
    outputSchema: z.object({
      changedFiles: z.array(z.string()),
      commitHash: z.string(),
    }),
    execute: async ({ inputData }) => {
      console.log(`[Workflow] Step "code-development" started`);
      console.log(`[Workflow]   Design doc: ${inputData.designDocPath} (${inputData.designDocContent.length} chars)`);

      // TODO: Replace with real Claude Code CLI spawn
      await new Promise((resolve) => setTimeout(resolve, 60000));

      const changedFiles = ['src/feature/index.js', 'src/feature/utils.js', 'src/feature/types.js'];
      const commitHash = 'mock-' + Date.now().toString(36);

      console.log(`[Workflow] Step "code-development" completed — ${changedFiles.length} files, commit: ${commitHash}`);
      return { changedFiles, commitHash };
    },
  });

  const testingStep = createStep({
    id: 'testing',
    inputSchema: z.object({
      changedFiles: z.array(z.string()),
      commitHash: z.string(),
    }),
    outputSchema: z.object({
      passed: z.boolean(),
      testReportPath: z.string(),
      summary: z.string(),
    }),
    execute: async ({ inputData }) => {
      console.log(`[Workflow] Step "testing" started`);
      console.log(`[Workflow]   Files: ${inputData.changedFiles.join(', ')}`);

      // TODO: Replace with real Claude Code CLI spawn
      await new Promise((resolve) => setTimeout(resolve, 60000));

      console.log(`[Workflow] Step "testing" completed — passed: true`);
      return {
        passed: true,
        testReportPath: 'docs/test-report.md',
        summary: `[Mock] All tests passed. ${inputData.changedFiles.length} files covered.`,
      };
    },
  });

  const codeReviewStep = createStep({
    id: 'code-review',
    inputSchema: z.object({
      passed: z.boolean(),
      testReportPath: z.string(),
      summary: z.string(),
    }),
    outputSchema: z.object({
      reviewReportPath: z.string(),
      approved: z.boolean(),
      comments: z.string(),
    }),
    execute: async ({ inputData }) => {
      console.log(`[Workflow] Step "code-review" started`);
      console.log(`[Workflow]   Tests passed: ${inputData.passed}`);

      // TODO: Replace with real Claude Code CLI spawn
      await new Promise((resolve) => setTimeout(resolve, 60000));

      const approved = inputData.passed;
      const comments = approved
        ? '[Mock] Code looks good. All tests pass. Approved.'
        : '[Mock] Tests are failing. Please fix before merging.';

      console.log(`[Workflow] Step "code-review" completed — approved: ${approved}`);
      return { reviewReportPath: 'docs/review.md', approved, comments };
    },
  });

  const workflow = createWorkflow({
    id: 'dev-workflow-v1',
    inputSchema: z.object({
      taskId: z.number(),
      taskTitle: z.string(),
      taskDescription: z.string(),
      requirementContent: z.string(),
      worktreePath: z.string(),
    }),
    outputSchema: z.object({
      reviewReportPath: z.string(),
      approved: z.boolean(),
      comments: z.string(),
    }),
  })
    .then(requirementDesignStep)
    .then(codeDevelopmentStep)
    .then(testingStep)
    .then(codeReviewStep);

  workflow.commit();
  return workflow;
}

export function getMastra() {
  if (!_mastra) throw new Error('Mastra not initialized. Call initWorkflows() first.');
  return _mastra;
}

export function getDevWorkflow() {
  if (!_devWorkflow) throw new Error('Workflow not initialized. Call initWorkflows() first.');
  return _devWorkflow;
}
